TEMPLATES = [
    {
        "display_name": "Nano Agent Offline",
        "id": "nc_tmpl:000000001",
        "description": "Send a notification to your desired destination when Spyderbat detects it is no longer receiving data from a Nano Agent.",
        "type": "agent_health",
        "config": {
            "schema_type": "event_opsflag",
            "condition": 'schema ~= "*:agent_offline:*" AND ephemeral = false AND agent_type="nano_agent"',
            "title": "Spyderbat Nano Agent Detected Offline",
            "message": "{{ __source__ }}",
            "additional_fields": {
                "details": {
                    "Agent UID": "{{ ref }}",
                    "Time": "{{ __hr_time__ }}",
                    "Source UID": "{{ muid }}",
                },
                "linkback_text": "View in Spyderbat",
                "linkback_url": "{{ __linkback__ }}",
                "slack_icon": ":red_circle:",
            },
        },
    },
    {
        "display_name": "Nano Agent Back Online",
        "id": "nc_tmpl:000000002",
        "description": "Send a notification to your desired destination when Spyderbat detects that a Nano Agent has come back online and is sending data.",
        "type": "agent_health",
        "config": {
            "schema_type": "event_opsflag",
            "condition": 'schema ~= "*:agent_online:*" AND agent_type="nano_agent"',
            "title": "Spyderbat Nano Agent Back Online",
            "message": "{{ __source__ }}",
            "additional_fields": {
                "details": {
                    "Agent UID": "{{ ref }}",
                    "Time": "{{ __hr_time__ }}",
                    "Source UID": "{{ muid }}",
                },
                "linkback_text": "View in Spyderbat",
                "linkback_url": "{{ __linkback__ }}",
                "slack_icon": ":large_green_circle:",
            },
        },
    },
    {
        "display_name": "Ephemeral Nano Agent Offline",
        "id": "nc_tmpl:000000003",
        "description": "Send a notification to your desired destination when Spyderbat detects it is no longer receiving data from an ephemeral Nano Agent (This is typically for Nano Agents on Kubernetes Nodes).",
        "type": "agent_health",
        "config": {
            "schema_type": "event_opsflag",
            "condition": 'schema ~= "*:agent_offline:*" AND ephemeral = true AND agent_type="nano_agent"',
            "title": "Ephemeral Spyderbat NanoAgent Detected Offline",
            "message": "{{ __source__ }}",
            "additional_fields": {
                "details": {
                    "Agent UID": "{{ ref }}",
                    "Time": "{{ __hr_time__ }}",
                    "Source UID": "{{ muid }}",
                },
                "linkback_text": "View in Spyderbat",
                "linkback_url": "{{ __linkback__ }}",
                "slack_icon": ":large_yellow_circle:",
            },
        },
    },
    {
        "display_name": "Clustermonitor Offline",
        "id": "nc_tmpl:000000004",
        "description": "Send a notification to your desired destination when Spyderbat detects it is no longer receiving data from a Clustermonitor.",
        "type": "agent_health",
        "config": {
            "schema_type": "event_opsflag",
            "condition": 'schema ~= "*:agent_offline:*" AND agent_type="clustermonitor"',
            "title": "Spyderbat Clustermonitor Detected Offline",
            "message": "{{ __source__ }}",
            "additional_fields": {
                "details": {
                    "Agent UID": "{{ ref }}",
                    "Time": "{{ __hr_time__ }}",
                    "Source UID": "{{ muid }}",
                },
                "linkback_text": "View in Spyderbat",
                "linkback_url": "{{ __linkback__ }}",
                "slack_icon": ":red_circle:",
            },
        },
    },
    {
        "display_name": "Clustermonitor Online",
        "id": "nc_tmpl:000000005",
        "description": "Send a notification to your desired destination when Spyderbat detects that a Clustermonitor has come back online and is sending data.",
        "type": "agent_health",
        "config": {
            "schema_type": "event_opsflag",
            "condition": 'schema ~= "*:agent_online:*" AND agent_type="clustermonitor"',
            "title": "Spyderbat Clustermonitor Detected Back Online",
            "message": "{{ __source__ }}",
            "additional_fields": {
                "details": {
                    "Agent UID": "{{ ref }}",
                    "Time": "{{ __hr_time__ }}",
                    "Source UID": "{{ muid }}",
                },
                "linkback_text": "View in Spyderbat",
                "linkback_url": "{{ __linkback__ }}",
                "slack_icon": ":large_green_circle:",
            },
        },
    },
    {
        "display_name": "Bat Offline",
        "id": "nc_tmpl:000000006",
        "description": "Send a notification to your desired destination when a Bat goes offline.",
        "type": "agent_health",
        "config": {
            "schema_type": "event_opsflag",
            "condition": 'schema ~= "*:bat_offline:*"',
            "title": "Spyderbat Bat Offline",
            "message": "{{ description }}\n\n{{ __source__ }}",
            "additional_fields": {
                "details": {
                    "Agent UID": "{{ ref }}",
                    "Time": "{{ __hr_time__ }}",
                    "Source UID": "{{ muid }}",
                    "Bat": "{{ bat_name }}",
                    "Severity": "{{ severity }}",
                },
                "linkback_text": "View in Spyderbat",
                "linkback_url": "{{ __linkback__ }}",
                "slack_icon": ":red_circle:",
            },
        },
    },
    {
        "display_name": "Bat Online",
        "id": "nc_tmpl:000000007",
        "description": "Send a notification to your desired destination when a Bat comes back online.",
        "type": "agent_health",
        "config": {
            "schema_type": "event_opsflag",
            "condition": 'schema ~= "*:bat_online:*"',
            "title": "Spyderbat Bat Back Online",
            "message": "{{ description }}\n\n{{ __source__ }}",
            "additional_fields": {
                "details": {
                    "Agent UID": "{{ ref }}",
                    "Time": "{{ __hr_time__ }}",
                    "Source UID": "{{ muid }}",
                    "Bat": "{{ bat_name }}",
                    "Severity": "{{ severity }}",
                },
                "linkback_text": "View in Spyderbat",
                "linkback_url": "{{ __linkback__ }}",
                "slack_icon": ":large_green_circle:",
            },
        },
    },
]
