apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: docker.io-coredns-policy
  type: container
  latestTimestamp: 1677247249.5528321
spec:
  containerSelector:
    image: docker.io/coredns/coredns:*
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kube-system
  processPolicy:
  - name: coredns
    exe:
    - /coredns
    id: coredns_0
    euser:
    - root
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'
    actions: []
