apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: eks/csi-attacher-policy
  type: container
  latestTimestamp: 1677247210.2956302
spec:
  containerSelector:
    image: '*eks/csi-attacher:*'
  podSelector:
    matchLabels:
      app: ebs-csi-controller
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/managed-by: EKS
      app.kubernetes.io/name: aws-ebs-csi-driver
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kube-system
  processPolicy:
  - name: csi-attacher
    exe:
    - /csi-attacher
    id: csi-attacher_0
    euser:
    - ec2-user
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'
    actions: []
