apiVersion: spyderbat/v1
kind: SpyderbatPolicy
metadata:
  name: eks-pause-policy
  type: container
  latestTimestamp: 1677261670.0456343
spec:
  containerSelector:
    image: '*eks/pause:*'   
  machineSelector:
    hostname: '*.ec2.internal'
  processPolicy:
  - name: pause
    exe:
    - /pause
    id: pause_0
    euser:
    - UID 65535
    - ec2-user
    - root
  networkPolicy:
    ingress: []
    egress: []
  response:
    default:
    - makeRedFlag:
        severity: info
        content: 'This is a provisional flag indicating a would-be policy violation. Use the `spyctl merge` command to tailor this policy to your environment, and update the severity as needed.'    
    actions: []
