apiVersion: v1
kind: Service
metadata:
  name: {{ include "spyctl-api-svc.fullname" . }}
  labels:
    {{- include "spyctl-api-svc.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "internal"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "spyctl-api-svc.selectorLabels" . | nindent 4 }}
  loadBalancerClass: service.k8s.aws/nlb
